// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiBoutique.Data;

#nullable disable

namespace WebApiBoutique.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222071104_NewDatabase")]
    partial class NewDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiBoutique.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ConfirmationToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastOtpResendAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<DateTime?>("OtpGeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OtpResendCount")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("WebApiBoutique.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("WebApiBoutique.Models.CustomerMeasurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeasurementId"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("GarmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("MeasurementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("MeasurementValue")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("inches");

                    b.HasKey("MeasurementId");

                    b.HasIndex("CustomerId", "Gender");

                    b.ToTable("CustomerMeasurements", t =>
                        {
                            t.HasCheckConstraint("CK_Gender", "Gender IN ('M', 'F')");

                            t.HasCheckConstraint("CK_MenChest", "NOT (Gender = 'M' AND MeasurementType = 'Chest' AND (MeasurementValue < 34 OR MeasurementValue > 52))");

                            t.HasCheckConstraint("CK_MenHips", "NOT (Gender = 'M' AND MeasurementType = 'Hips' AND (MeasurementValue < 34 OR MeasurementValue > 48))");

                            t.HasCheckConstraint("CK_MenNeck", "NOT (Gender = 'M' AND MeasurementType = 'Neck' AND (MeasurementValue < 14 OR MeasurementValue > 20))");

                            t.HasCheckConstraint("CK_MenShoulder", "NOT (Gender = 'M' AND MeasurementType = 'Shoulder' AND (MeasurementValue < 15 OR MeasurementValue > 22))");

                            t.HasCheckConstraint("CK_MenSleeveLength", "NOT (Gender = 'M' AND MeasurementType = 'Sleeve Length' AND (MeasurementValue < 22 OR MeasurementValue > 27))");

                            t.HasCheckConstraint("CK_MenWaist", "NOT (Gender = 'M' AND MeasurementType = 'Waist' AND (MeasurementValue < 28 OR MeasurementValue > 44))");

                            t.HasCheckConstraint("CK_WomenBust", "NOT (Gender = 'F' AND MeasurementType = 'Bust' AND (MeasurementValue < 30 OR MeasurementValue > 46))");

                            t.HasCheckConstraint("CK_WomenHips", "NOT (Gender = 'F' AND MeasurementType = 'Hips' AND (MeasurementValue < 32 OR MeasurementValue > 48))");

                            t.HasCheckConstraint("CK_WomenShoulder", "NOT (Gender = 'F' AND MeasurementType = 'Shoulder' AND (MeasurementValue < 13 OR MeasurementValue > 19))");

                            t.HasCheckConstraint("CK_WomenUpperArm", "NOT (Gender = 'F' AND MeasurementType = 'Upper Arm' AND (MeasurementValue < 10 OR MeasurementValue > 16))");

                            t.HasCheckConstraint("CK_WomenWaist", "NOT (Gender = 'F' AND MeasurementType = 'Waist' AND (MeasurementValue < 24 OR MeasurementValue > 40))");
                        });
                });

            modelBuilder.Entity("WebApiBoutique.Models.DTOs.CustomerDeliveryDTO", b =>
                {
                    b.Property<decimal>("AdvanceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AdvanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("WebApiBoutique.Models.DTOs.CustomerMeasurementDTO", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FabricColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FabricImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("WebApiBoutique.Models.DTOs.CustomerPaymentDTO", b =>
                {
                    b.Property<decimal>("BalanceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<decimal>("ReceivedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("WebApiBoutique.Models.DTOs.PasswordHistoryDTO", b =>
                {
                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("WebApiBoutique.Models.Delivery_Status", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<decimal>("AdvanceAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AdvanceDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeliveryId");

                    b.HasIndex("CustomerId");

                    b.ToTable("DeliveryStatuses");
                });

            modelBuilder.Entity("WebApiBoutique.Models.M_KurtaMen", b =>
                {
                    b.Property<int>("KurtaMenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KurtaMenId"));

                    b.Property<decimal>("Armhole")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Chest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KurtaLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<decimal>("NeckDepth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NeckWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShoulderWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SideSlitHeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waist")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("KurtaMenId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("TypeId");

                    b.ToTable("KurtaMen");
                });

            modelBuilder.Entity("WebApiBoutique.Models.M_PantMen", b =>
                {
                    b.Property<int>("PantMenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PantMenId"));

                    b.Property<decimal>("BottomOpening")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Calf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CrotchDepth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FlyLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InseamLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Knee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<decimal>("OutseamLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Thigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waist")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PantMenId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("TypeId");

                    b.ToTable("PantMen");
                });

            modelBuilder.Entity("WebApiBoutique.Models.M_PayjamaMen", b =>
                {
                    b.Property<int>("PayjamaMenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayjamaMenId"));

                    b.Property<decimal>("BottomOpening")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Calf")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CrotchDepth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InseamLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Knee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<decimal>("OutseamLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Thigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waist")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PayjamaMenId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("TypeId");

                    b.ToTable("PayjamaMen");
                });

            modelBuilder.Entity("WebApiBoutique.Models.M_ShirtMen", b =>
                {
                    b.Property<int>("ShirtMenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShirtMenId"));

                    b.Property<decimal>("Armhole")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BackWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Chest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CuffCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<decimal>("NeckCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShirtLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShoulderWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waist")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ShirtMenId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("TypeId");

                    b.ToTable("ShirtMen");
                });

            modelBuilder.Entity("WebApiBoutique.Models.M_TShirtMen", b =>
                {
                    b.Property<int>("TShirtMenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TShirtMenId"));

                    b.Property<decimal>("Armhole")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Chest")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<decimal>("NeckWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShoulderWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TShirtLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waist")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TShirtMenId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("TypeId");

                    b.ToTable("TShirtMen");
                });

            modelBuilder.Entity("WebApiBoutique.Models.Measurement", b =>
                {
                    b.Property<int>("MeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeasurementId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FabricColor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FabricImage")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("MeasurementId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TypeId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("WebApiBoutique.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EstimatedDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("MeasurementId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebApiBoutique.Models.PasswordHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordHistories");
                });

            modelBuilder.Entity("WebApiBoutique.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentDate");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("WebApiBoutique.Models.TypeModel", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TypeId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("WebApiBoutique.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApiBoutique.Models.W_BlazerWomen", b =>
                {
                    b.Property<int>("BlazerWomenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlazerWomenId"));

                    b.Property<decimal>("Armhole")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BackWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BlazerLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bust")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LapelDepth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<decimal>("NeckWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShoulderWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waist")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BlazerWomenId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("TypeId");

                    b.ToTable("Blazer_Women");
                });

            modelBuilder.Entity("WebApiBoutique.Models.W_Frock", b =>
                {
                    b.Property<int>("FrockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrockId"));

                    b.Property<decimal>("Armhole")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bust")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FlareWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FrockLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<decimal>("NeckDepthBack")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NeckDepthFront")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NeckWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShoulderWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waist")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YokeDepth")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FrockId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("TypeId");

                    b.ToTable("Frocks");
                });

            modelBuilder.Entity("WebApiBoutique.Models.W_KurtiWomen", b =>
                {
                    b.Property<int>("KurtiWomenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KurtiWomenId"));

                    b.Property<decimal>("Armhole")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bust")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Hip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KurtiLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<decimal>("NeckDepthBack")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NeckDepthFront")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NeckWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShoulderToBust")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShoulderToWaist")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShoulderWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SideSlitHeight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waist")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("KurtiWomenId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("TypeId");

                    b.ToTable("KurtiWomen");
                });

            modelBuilder.Entity("WebApiBoutique.Models.W_PayjamaWomen", b =>
                {
                    b.Property<int>("PayjamaWomenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayjamaWomenId"));

                    b.Property<decimal>("BottomOpening")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CalfCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CrotchDepth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HipCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InseamLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("KneeCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<decimal>("OutseamLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThighCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("WaistCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PayjamaWomenId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("TypeId");

                    b.ToTable("PayjamaWomen");
                });

            modelBuilder.Entity("WebApiBoutique.Models.W_TopWomen", b =>
                {
                    b.Property<int>("TopWomenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TopWomenId"));

                    b.Property<decimal>("Armhole")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Bust")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Hip")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MeasurementId")
                        .HasColumnType("int");

                    b.Property<decimal>("NeckDepth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NeckWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShoulderWidth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveCircumference")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SleeveLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TopLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Waist")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TopWomenId");

                    b.HasIndex("MeasurementId");

                    b.HasIndex("TypeId");

                    b.ToTable("TopWomen");
                });

            modelBuilder.Entity("WebApiBoutique.Models.CustomerMeasurement", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebApiBoutique.Models.Delivery_Status", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Customer", "Customer")
                        .WithMany("Deliveries")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("WebApiBoutique.Models.M_KurtaMen", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApiBoutique.Models.M_PantMen", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApiBoutique.Models.M_PayjamaMen", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApiBoutique.Models.M_ShirtMen", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApiBoutique.Models.M_TShirtMen", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApiBoutique.Models.Measurement", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Customer", "Customer")
                        .WithMany("Measurements")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.TypeModel", "Type")
                        .WithMany("Measurements")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApiBoutique.Models.Order", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId");

                    b.Navigation("Customer");

                    b.Navigation("Measurement");
                });

            modelBuilder.Entity("WebApiBoutique.Models.PasswordHistory", b =>
                {
                    b.HasOne("WebApiBoutique.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("WebApiBoutique.Models.Payment", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Customer", null)
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId");

                    b.HasOne("WebApiBoutique.Models.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebApiBoutique.Models.W_BlazerWomen", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApiBoutique.Models.W_Frock", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApiBoutique.Models.W_KurtiWomen", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApiBoutique.Models.W_PayjamaWomen", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApiBoutique.Models.W_TopWomen", b =>
                {
                    b.HasOne("WebApiBoutique.Models.Measurement", "Measurement")
                        .WithMany()
                        .HasForeignKey("MeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApiBoutique.Models.TypeModel", "Type")
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Measurement");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("WebApiBoutique.Models.Customer", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Measurements");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WebApiBoutique.Models.Order", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WebApiBoutique.Models.TypeModel", b =>
                {
                    b.Navigation("Measurements");
                });
#pragma warning restore 612, 618
        }
    }
}
